/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FixRouteImport } from './routes/fix'
import { Route as IndexRouteImport } from './routes/index'

const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FixRoute = FixRouteImport.update({
  id: '/fix',
  path: '/fix',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fix': typeof FixRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/referral': typeof ReferralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fix': typeof FixRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/referral': typeof ReferralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fix': typeof FixRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/referral': typeof ReferralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fix' | '/history' | '/login' | '/profil' | '/referral'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fix' | '/history' | '/login' | '/profil' | '/referral'
  id:
    | '__root__'
    | '/'
    | '/fix'
    | '/history'
    | '/login'
    | '/profil'
    | '/referral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixRoute: typeof FixRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  ReferralRoute: typeof ReferralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix': {
      id: '/fix'
      path: '/fix'
      fullPath: '/fix'
      preLoaderRoute: typeof FixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixRoute: FixRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  ReferralRoute: ReferralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
